version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: nestjs-backend
    env_file: ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"

volumes:
  mongo_data:
